title: Ayham's Blog # The title of the blog
author: Ayham Hasan # Your name 
email: contact@ayham.dev # your email shown in the footer
url: ayham.dev # this is your site's root address.
baseurl: /
description: > # this means to ignore newlines until "show_excerpts:"
  A place of love, hate, and wonder.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "/assets/pfp.png" # avatar in about page
  about_you: A computer nerd with a site # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  AyhamHasan
    # rss: RSS
    # dribbble: 
    # facebook: huangyz0918
    # flickr:   
    # instagram: 
    linkedin: ayham-hasan-876347157
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
